# 向量

**向量**是一组有序排列的数。通过次序索引，可以得到每个单独的数（元素）。  

行向量：
$
X= \begin{bmatrix}
x_1 & x_2 & \cdots & x_n
\end{bmatrix}
$

列向量：
$
X= \begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}
$

向量中的元素可以代表：
- 某个事物的若干种状态
- 某个对象的若干属性
- 某个多项式的若干个系数$

In [1]:
import numpy as np

In [2]:
# 行向量
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
# 列向量
b = np.array([[1], [2], [3], [4], [5]])
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
# 向量转置
b.T

array([[1, 2, 3, 4, 5]])

In [5]:
# 冒号生成向量
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [6]:
# 冒号指定步长
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [7]:
# 函数生成向量，默认数量
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [8]:
# 指定数量
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [9]:
# 对数等分
np.logspace(1, 5, 3)

array([1.e+01, 1.e+03, 1.e+05])