# 矩阵

**矩阵**是二维数组，其中每个元素由两个索引确定。

$$
$A \in \mathbb{R}^{m \times n} = \begin{bmatrix} 
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
a_{31} & a_{32} & \dots & a_{3n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn} 
\end{bmatrix}
$$

矩阵可以表示一张 m x n 个像素组成的图片。也可以表示 m 个用户，每个用户有 n 个特征的数据集。

当 m = n 时，该矩阵称为**方阵**。

**单位矩阵**，对角线元素为 1，其他全部元素为 0 的矩阵。

In [1]:
import numpy as np

In [2]:
# 2 x 3 矩阵
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# 取第 1 行
a[0, :]

array([1, 2, 3])

In [4]:
# 取第 2 列
a[:, 1]

array([2, 5])

In [5]:
# 取第 1 行，第 3 列
a[0, 2]

np.int64(3)

In [6]:
# 3 x 3 的方阵
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# 取下三角
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [8]:
# 取上三角
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [9]:
# 取主对角线
np.diag(a)

array([1, 5, 9])

In [10]:
# n x m 的单位矩阵
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
# n x m 的全 1 矩阵
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# n x m 的全 0 矩阵
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# n x m 的随机矩阵
np.random.rand(3, 4)

array([[0.09773098, 0.91796188, 0.1145244 , 0.90375112],
       [0.08363592, 0.39572352, 0.55845489, 0.81720591],
       [0.82098777, 0.91392866, 0.99387245, 0.02371596]])