# 张量

**张量**是基于向量和矩阵的推广，一般而言，超过两维的数组叫做张量。例如：可以将任意一张彩色图片表示成一个三阶张量，三个维度分别是图片的 R, G, B 三种颜色分量的矩阵。

- 标量可以看作是零阶张量
- 向量可以看作是一阶张量
- 矩阵可以看作是二阶张量

In [1]:
import numpy as np

# 定义三个 3×3 的子矩阵（张量的“层”）
slice1 = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 8]
])

slice2 = np.array([
    [2, 3, 4],
    [5, 6, 7],
    [7, 8, 9]
])

slice3 = np.array([
    [3, 4, 5],
    [4, 5, 6],
    [5, 6, 7]
])

# 堆叠为 3×3×3 的三维张量
X = np.array([slice1, slice2, slice3])

# 验证张量形状与元素
print("构造的三维张量：")
print(X)
print("\n张量形状（层, 行, 列）：", X.shape)
print("\n验证第一层（X[0]）：\n", X[0])
print("\n验证第二层（X[1]）：\n", X[1])
print("\n验证第三层（X[2]）：\n", X[2])

构造的三维张量：
[[[1 2 3]
  [3 4 5]
  [6 7 8]]

 [[2 3 4]
  [5 6 7]
  [7 8 9]]

 [[3 4 5]
  [4 5 6]
  [5 6 7]]]

张量形状（层, 行, 列）： (3, 3, 3)

验证第一层（X[0]）：
 [[1 2 3]
 [3 4 5]
 [6 7 8]]

验证第二层（X[1]）：
 [[2 3 4]
 [5 6 7]
 [7 8 9]]

验证第三层（X[2]）：
 [[3 4 5]
 [4 5 6]
 [5 6 7]]
