# 标量、向量、矩阵的基本运算

In [1]:
import numpy as np

## 数乘运算

**向量的数乘**

$$
\lambda X = X \lambda = \begin{bmatrix}
\lambda x_1 & \lambda x_2 & \dots & \lambda x_n
\end{bmatrix}
$$

**矩阵的数乘**

$$
\lambda A = A \lambda = \begin{bmatrix}
\lambda a_{11} & \lambda a_{12} & \dots & \lambda a_{1n} \\
\lambda a_{21} & \lambda a_{22} & \dots & \lambda a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
\lambda a_{m1} & \lambda a_{m2} & \dots & \lambda a_{mn}
\end{bmatrix}
$$

In [2]:
# 向量数乘
a = np.array([4, 10, 6])
a, 2 * a

(array([ 4, 10,  6]), array([ 8, 20, 12]))

In [3]:
# 矩阵数乘
b = np.array([[4, 10, 6], [-2, 4, 0], [0, 4, 5]])
b, 2 * b

(array([[ 4, 10,  6],
        [-2,  4,  0],
        [ 0,  4,  5]]),
 array([[ 8, 20, 12],
        [-4,  8,  0],
        [ 0,  8, 10]]))

## 加法

相加的两个向量或矩阵的维度必须相同。

**向量加法**

$$
X + Y = \begin{bmatrix}
x_1 + y_1 & x_2 + y_2 & \dots & x_n + y_n
\end{bmatrix}
$$

**矩阵加法**

$$
A + B = \begin{bmatrix}
a_{11} + b_{11} & a_{12} + b_{12} & \dots & a_{1n} + b_{1n}  \\
a_{21} + b_{21} & a_{22} + b_{22} & \dots & a_{2n} + b_{2n}  \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \dots & a_{mn} + b_{mn} 
\end{bmatrix}
$$

**矩阵加行向量**

$$
A + Y = \begin{bmatrix}
a_{11} + y_1 & a_{12} + y_2 & \dots & a_{1n} + y_n  \\
a_{21} + y_1 & a_{22} + y_2 & \dots & a_{2n} + y_n  \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} + y_1 & a_{m2} + y_2 & \dots & a_{mn} + y_n 
\end{bmatrix}
$$

In [4]:
# 向量相加
c = np.array([4, 10, 6])
d = np.array([1, 2, 3])
c, d, c + d

(array([ 4, 10,  6]), array([1, 2, 3]), array([ 5, 12,  9]))

In [5]:
# 矩阵相加
e = np.array([[4, 10, 6], [-2, 4, 0], [0, 4, 5]])
f = np.array([[1, 2, 3], [3, 4, 5], [7, 8, 9]])
e, f, e + f

(array([[ 4, 10,  6],
        [-2,  4,  0],
        [ 0,  4,  5]]),
 array([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]]),
 array([[ 5, 12,  9],
        [ 1,  8,  5],
        [ 7, 12, 14]]))

In [6]:
# 矩阵 + 行向量，广播，行向量加到矩阵的每一行
e, d, e + d

(array([[ 4, 10,  6],
        [-2,  4,  0],
        [ 0,  4,  5]]),
 array([1, 2, 3]),
 array([[ 5, 12,  9],
        [-1,  6,  3],
        [ 1,  6,  8]]))

## 向量的乘法或内积

相乘的两个向量的维度必须相同。

$$
XY = X^{T}Y = \begin{bmatrix}
x_1y_1 & x_2y_2 & \dots & x_ny_n
\end{bmatrix}
$$

In [7]:
g = np.array([1, 0, 3])
h = np.array([1, 2, 3])
g, h

(array([1, 0, 3]), array([1, 2, 3]))

In [8]:
# 向量内积
np.dot(g, h)

np.int64(10)

In [9]:
# 向量叉积
np.cross(g, h)

array([-6,  0,  2])

In [10]:
# 验证叉积与原向量垂直
np.dot(np.cross(g, h), g)
np.dot(np.cross(g, h), h)

np.int64(0)

In [11]:
# 向量点乘，对应位相乘
g * h

array([1, 0, 9])

## 矩阵乘法

有两个矩阵，其中 $A \in R^{m \times k}$， $B \in R^{k \times n}$。

则：
$$
C = A \times B
$$

$$
C \in R^{m \times n}
$$

其中，矩阵 C 中的每个元素

$$
C_{i,j} = \sum_{k} A_{i,k} B_{k,j}
$$

In [12]:
j = np.array([[1, 0, 3], [0, 2, 4]])
k = np.array([[1, 1], [2, 0], [3, 2]])
j, k

(array([[1, 0, 3],
        [0, 2, 4]]),
 array([[1, 1],
        [2, 0],
        [3, 2]]))

In [13]:
# 矩阵相乘
np.dot(j, k)

array([[10,  7],
       [16,  8]])

In [14]:
# 矩阵乘法的应用

# 产品 a 和 产品 b 的三项成本构成
l = np.array([[1, 1], [2, 3], [3, 5]])
# 产品a 和 产品b 四个季度的产量
m = np.array([[100, 150, 180, 120], [300, 200, 240, 180]])

# 求两个产品在每个季度的总成本
quarterly_costs = np.dot(l, m)
quarterly_costs

array([[ 400,  350,  420,  300],
       [1100,  900, 1080,  780],
       [1800, 1450, 1740, 1260]])

## 矩阵除法和逆矩阵

逆矩阵相当于倒数。矩阵（方阵）A 的逆矩阵 $A^{-1}$ 满足

$$
A^{-1}A=I_n
$$

In [15]:
n = np.array([[2, 3], [4, 5]])
o = np.linalg.inv(n)
n, o

(array([[2, 3],
        [4, 5]]),
 array([[-2.5,  1.5],
        [ 2. , -1. ]]))

In [16]:
# 验证逆矩阵
np.dot(n, o)

array([[1., 0.],
       [0., 1.]])

## 矩阵转置

如果：
$$
a_{ij} \in A, A \in R^{m \times n}
$$

则：
$$
a_{ji} \in A^T, A^T \in R^{n \times m}
$$

In [17]:
k, k.T

(array([[1, 1],
        [2, 0],
        [3, 2]]),
 array([[1, 2, 3],
        [1, 0, 2]]))