# 矩阵和向量属性

In [1]:
import numpy as np
from IPython.display import display, Math

def matrix_to_latex(matrix, precision=2):
    """
    将 NumPy 数组转换为 LaTeX 格式的矩阵字符串。
    
    参数:
    matrix: NumPy 数组
    precision: 浮点数精度（小数位数）
    """
    # 确保是二维数组
    if matrix.ndim == 1:
        matrix = matrix.reshape(1, -1) # 将一维数组转为行向量
    
    rows = []
    for row in matrix:
        # 格式化每个元素，控制精度
        row_str = " & ".join([f"{x:.{precision}f}" if isinstance(x, (int, float)) else str(x) for x in row])
        rows.append(row_str)
    
    # 使用 bmatrix 环境（带方括号的矩阵）
    latex_str = r"\begin{bmatrix}" + " \\\\ ".join(rows) + r"\end{bmatrix}"
    return latex_str

## 函数

函数是映射 $f: A \to B$

In [2]:
# 函数的参数可以是标量

x = 4
y = np.sqrt(x)
z = np.sin(y)

display(Math(f'y={y}, z={z:.2f}'))

<IPython.core.display.Math object>

In [3]:
# 函数的参数可以是向量

A = np.array([4, 5, 6])
B = np.array([1, 2, 3])
A_B = np.dot(A, B)  # 向量点积

display(Math(f'A={matrix_to_latex(A)}, B={matrix_to_latex(B)}'))
display(Math(f'A \\times B = {A_B}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [4]:
# 函数的参数可以是矩阵
C = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
diag_C = np.diag(C)   # 主对角线

display(Math(f'C = {matrix_to_latex(C)}'))
display(Math(f'diag(C) = {matrix_to_latex(diag_C)}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## 向量范数

In [5]:
V = np.array([2, 3, -5, -7])

**1 范数**：向量各元素绝对值之和

$$\| \mathbf{X} \|_1 = \sum_{i=1}^{n} \lvert x_i \rvert$$

In [6]:
NV1 = np.linalg.norm(V, 1)

display(Math(f'V = {matrix_to_latex(V)}'))
display(Math(rf'\| \mathbf{{V}} \|_1 = {NV1}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

**2 范数**：欧几里得范数（向量模长）

$$\| \mathbf{X} \|_2 = \sqrt{ \sum_{i=1}^{n} \lvert x_i \rvert^2 }$$

In [7]:
NV2 = np.linalg.norm(V, 2)

display(Math(f'V = {matrix_to_latex(V)}'))
display(Math(rf'\| \mathbf{{V}} \|_2 = {NV2:.2f}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

**P 范数**

$$\| \mathbf{X} \|_p = \left( \sum_{i=1}^{n} \lvert x_i \rvert^p \right)^{1/p}$$

In [8]:
p = 3
NV3 = np.linalg.norm(V, p)

display(Math(f'V = {matrix_to_latex(V)}'))
display(Math(rf'\| \mathbf{{V}} \|_3 = {NV3:.2f}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

**正无穷范数**：向量元素绝对值的最大值

$$\| \mathbf{x} \|_\infty = \max_{1 \le i \le n} \lvert x_i \rvert$$

In [9]:
V, np.linalg.norm(V, np.inf)

(array([ 2,  3, -5, -7]), np.float64(7.0))

**负无穷范数**：向量元素绝对值的最小值

$$\| \mathbf{x} \|_{-\infty} = \min_{1 \le i \le n} \lvert x_i \rvert$$

In [10]:
V, np.linalg.norm(V, -np.inf)

(array([ 2,  3, -5, -7]), np.float64(2.0))

## 矩阵范数

**1 范数**：矩阵每列元素绝对值之和的最大值

$$\| \mathbf{A} \|_1 = \max_{1 \le j \le n} \sum_{i=1}^{m} \lvert a_{ij} \rvert$$

In [11]:
A = np.array([[-1, 0, 5], [2, 4, 6], [0, 4, 5]])
A, np.linalg.norm(A, 1)

(array([[-1,  0,  5],
        [ 2,  4,  6],
        [ 0,  4,  5]]),
 np.float64(16.0))

**2 范数**i：也称为欧几里德范数或谱范数。矩阵 $A^TA$ 的最大特征值的平方根

$$
\left\|A\right\|_{2} = \sqrt{\lambda_{\text{max}}\left(A^{T} A\right)}
$$

In [12]:
A, np.linalg.norm(A, 2)

(array([[-1,  0,  5],
        [ 2,  4,  6],
        [ 0,  4,  5]]),
 np.float64(10.562480108859397))

In [13]:
# 验证矩阵 2 范数的计算过程

display(Math(f'A={matrix_to_latex(A)}'))
display(Math(f'A^T={matrix_to_latex(A.T)}'))

A_t_A = np.dot(A.T, A)
display(Math(f'A^T \\times A ={matrix_to_latex(A_t_A)}'))

eigenvalues = np.linalg.eigvals(A_t_A)  # 计算特征值
display(Math(f'\\lambda(A^{{T}} A) ={matrix_to_latex(eigenvalues)}'))

max_eigenvalue = np.max(eigenvalues)  # 取最大特征值
display(Math(f'\\lambda_{{\\max}}(A^{{T}} A) ={max_eigenvalue:.2f}'))

eig_norm = np.sqrt(max_eigenvalue)  # 平方根得到 2 范数
display(Math(f'\\left\\|A\\right\\|_{{2}} = \\sqrt {{\\lambda_{{\\max}}(A^{{T}} A)}} = {eig_norm:.2f}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

**无穷范数**：也叫行范数，矩阵每行元素绝对值之和的最大值

$$\| \mathbf{A} \|_\infty = \max_{1 \le i \le m} \sum_{j=1}^{n} \lvert a_{ij} \rvert$$

In [14]:
A, np.linalg.norm(A, np.inf)

(array([[-1,  0,  5],
        [ 2,  4,  6],
        [ 0,  4,  5]]),
 np.float64(12.0))

In [15]:
# 秩，极大线性无关组的数量
np.linalg.matrix_rank(A)

np.int64(3)

## 特征值和特征向量

In [16]:
# 特征值和特征向量
f = np.array([[2, 1, 0], [1, 3, 1], [0, 1, 4]])
np.linalg.eig(f)

EigResult(eigenvalues=array([1.26794919, 3.        , 4.73205081]), eigenvectors=array([[-0.78867513, -0.57735027,  0.21132487],
       [ 0.57735027, -0.57735027,  0.57735027],
       [-0.21132487,  0.57735027,  0.78867513]]))