# 矩阵

In [3]:
import numpy as np

In [4]:
# 2 x 3 矩阵
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 取第 1 行
a[0, :]

array([1, 2, 3])

In [6]:
# 取第 2 列
a[:, 1]

array([2, 5])

In [7]:
# 取第 1 行，第 3 列
a[0, 2]

np.int64(3)

In [8]:
# 3 x 3 的方阵
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# 取下三角
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [21]:
# 取上三角
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [22]:
# 取主对角线
np.diag(a)

array([1, 5, 9])

In [23]:
# n x m 的单位矩阵
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
# n x m 的全 1 矩阵
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
# n x m 的全 0 矩阵
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
# n x m 的随机矩阵
np.random.rand(3, 4)

array([[0.61392346, 0.34265805, 0.19180627, 0.05531802],
       [0.6893179 , 0.11481727, 0.27639989, 0.49849249],
       [0.70874871, 0.15077955, 0.68168747, 0.53585267]])