# 标量、向量、矩阵的基本运算

In [1]:
import numpy as np

In [2]:
# 标量乘向量
a = np.array([4, 10, 6])
a, 2 * a

(array([ 4, 10,  6]), array([ 8, 20, 12]))

In [3]:
# 标量乘矩阵
b = np.array([[4, 10, 6], [-2, 4, 0], [0, 4, 5]])
b, 2 * b

(array([[ 4, 10,  6],
        [-2,  4,  0],
        [ 0,  4,  5]]),
 array([[ 8, 20, 12],
        [-4,  8,  0],
        [ 0,  8, 10]]))

In [4]:
# 向量加向量
c = np.array([4, 10, 6])
d = np.array([1, 2, 3])
c, d, c + d

(array([ 4, 10,  6]), array([1, 2, 3]), array([ 5, 12,  9]))

In [5]:
# 矩阵加矩阵
e = np.array([[4, 10, 6], [-2, 4, 0], [0, 4, 5]])
f = np.array([[1, 2, 3], [3, 4, 5], [7, 8, 9]])
e, f, e + f

(array([[ 4, 10,  6],
        [-2,  4,  0],
        [ 0,  4,  5]]),
 array([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]]),
 array([[ 5, 12,  9],
        [ 1,  8,  5],
        [ 7, 12, 14]]))

In [6]:
# 矩阵 + 行向量，广播，行向量加到矩阵的每一行
e, d, e + d

(array([[ 4, 10,  6],
        [-2,  4,  0],
        [ 0,  4,  5]]),
 array([1, 2, 3]),
 array([[ 5, 12,  9],
        [-1,  6,  3],
        [ 1,  6,  8]]))

# 向量的乘法或内积

In [7]:
g = np.array([1, 0, 3])
h = np.array([1, 2, 3])
g, h

(array([1, 0, 3]), array([1, 2, 3]))

In [9]:
# 向量内积
np.dot(g, h)

np.int64(10)

In [21]:
# 向量叉积
np.cross(g, h)

array([-6,  0,  2])

In [ ]:
# 验证叉积与原向量垂直
np.dot(np.cross(g, h), g)
np.dot(np.cross(g, h), h)


np.int64(0)

In [ ]:
# 向量点乘，对应位相乘
g * h

array([1, 0, 9])

# 矩阵乘法

In [8]:
j = np.array([[1, 0, 3], [0, 2, 4]])
k = np.array([[1, 1], [2, 0], [3, 2]])
j, k

(array([[1, 0, 3],
        [0, 2, 4]]),
 array([[1, 1],
        [2, 0],
        [3, 2]]))

In [ ]:
# 矩阵相乘
np.dot(j, k)

array([[10,  7],
       [16,  8]])

In [ ]:
# 矩阵乘法应用

# 产品a 和 产品b 的三项成本构成
l = np.array([[1, 1], [2, 3], [3, 5]])
# 产品a 和 产品b 四个季度的产量
m = np.array([[100, 150, 180, 120], [300, 200, 240, 180]])

# 求两个产品在每个季度的总成本
quarterly_costs = np.dot(l, m)
quarterly_costs

array([[ 400,  350,  420,  300],
       [1100,  900, 1080,  780],
       [1800, 1450, 1740, 1260]])

# 矩阵除法和逆矩阵

In [9]:
n = np.array([[2, 3], [4, 5]])
o = np.linalg.inv(n)
n, o

(array([[2, 3],
        [4, 5]]),
 array([[-2.5,  1.5],
        [ 2. , -1. ]]))

In [18]:
# 验证逆矩阵
np.dot(n, o)

array([[1., 0.],
       [0., 1.]])

# 矩阵转置

In [10]:
k, k.T

(array([[1, 1],
        [2, 0],
        [3, 2]]),
 array([[1, 2, 3],
        [1, 0, 2]]))